"""rulesets catalogue (§4.4)

Versioned, immutable master-LOR storage: rulesets + claim-type sections +
requirement rules + the rule<->claim-type join. Enum types already exist (0002),
so every ENUM here is create_type=False.

Revision ID: 0004_rulesets
Revises: 0003_identity_blobs
Create Date: 2026-08-09
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004_rulesets'
down_revision: Union[str, None] = '0003_identity_blobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('insurer_id', sa.UUID(), nullable=True),
    sa.Column('ruleset_slug', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('coverage_report', sa.Text(), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('draft','active','retired')", name=op.f('ck_rulesets_status_valid')),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], name=op.f('fk_rulesets_activated_by_users')),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], name=op.f('fk_rulesets_insurer_id_insurers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rulesets')),
    sa.UniqueConstraint('ruleset_slug', 'version', name='slug_version')
    )
    op.create_index('rulesets_one_active', 'rulesets', ['ruleset_slug'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('requirement_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ruleset_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('verification', postgresql.ENUM('classified', 'attested', name='req_verification', create_type=False), server_default=sa.text("'attested'"), nullable=False),
    sa.Column('accepts', postgresql.ARRAY(postgresql.ENUM('policy_schedule', 'premium_receipt', 'govt_id', 'tax_invoice', 'stock_register', 'menu_or_price_list', 'marketing_or_other_commercial', 'damage_photograph', 'fir_report', 'fire_brigade_report', 'repair_estimate', 'repair_bill', 'bank_proof', 'medical_certificate', 'driving_licence', 'vehicle_rc', 'unreadable', 'unknown', name='document_kind', create_type=False)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('severity', postgresql.ENUM('blocking', 'advisory', name='req_severity', create_type=False), server_default=sa.text("'advisory'"), nullable=False),
    sa.Column('when_categories', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('when_item_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('when_account_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint("verification <> 'attested' OR cardinality(accepts) = 0", name=op.f('ck_requirement_rules_attested_accepts_empty')),
    sa.CheckConstraint("verification <> 'classified' OR cardinality(accepts) > 0", name=op.f('ck_requirement_rules_classified_accepts_present')),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], name=op.f('fk_requirement_rules_ruleset_id_rulesets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_rules')),
    sa.UniqueConstraint('ruleset_id', 'requirement_id', name='requirement_id')
    )
    op.create_index('requirement_rules_accepts_gin', 'requirement_rules', ['accepts'], unique=False, postgresql_using='gin')
    op.create_table('ruleset_claim_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ruleset_id', sa.UUID(), nullable=False),
    sa.Column('section_key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], name=op.f('fk_ruleset_claim_types_ruleset_id_rulesets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ruleset_claim_types')),
    sa.UniqueConstraint('ruleset_id', 'section_key', name='section_key')
    )
    op.create_table('requirement_rule_claim_types',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('claim_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_type_id'], ['ruleset_claim_types.id'], name=op.f('fk_requirement_rule_claim_types_claim_type_id_ruleset_claim_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['requirement_rules.id'], name=op.f('fk_requirement_rule_claim_types_rule_id_requirement_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'claim_type_id', name=op.f('pk_requirement_rule_claim_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_rule_claim_types')
    op.drop_table('ruleset_claim_types')
    op.drop_index('requirement_rules_accepts_gin', table_name='requirement_rules', postgresql_using='gin')
    op.drop_table('requirement_rules')
    op.drop_index('rulesets_one_active', table_name='rulesets', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('rulesets')
    # ### end Alembic commands ###
