"""claim aggregate

Revision ID: 0005_claims
Revises: 0004_rulesets
Create Date: 2026-08-09 16:12:09.060759+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005_claims'
down_revision: Union[str, None] = '0004_rulesets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_ref', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('insurer_id', sa.UUID(), nullable=True),
    sa.Column('ruleset_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('processing', 'completed', 'awaiting_documents', 'failed', name='claim_status', create_type=False), server_default=sa.text("'processing'"), nullable=False),
    sa.Column('account_type', postgresql.ENUM('personal', 'commercial', 'insurance', name='account_type', create_type=False), nullable=False),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('event_description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('event_item_type', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('latest_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latest_lor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('claim_type_key', sa.Text(), nullable=True),
    sa.Column('claim_type_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('claim_type_source', sa.Text(), nullable=True),
    sa.Column('claim_type_candidates', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('claim_type_ambiguous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('intake_ok', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('awaiting_documents', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('kyc_status', sa.Text(), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("claim_type_source <> 'user_override' OR claim_type_key IS NOT NULL", name=op.f('ck_claims_override_needs_type')),
    sa.CheckConstraint("claim_type_source IS NULL OR claim_type_source IN ('inferred','user_override')", name=op.f('ck_claims_claim_type_source_valid')),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], name=op.f('fk_claims_insurer_id_insurers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], name=op.f('fk_claims_ruleset_id_rulesets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_claims_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('claim_ref', name=op.f('uq_claims_claim_ref'))
    )
    op.create_index('claims_open', 'claims', ['status'], unique=False, postgresql_where=sa.text("status IN ('processing','awaiting_documents')"))
    op.create_index('claims_user_recent', 'claims', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('claim_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('outcome', postgresql.ENUM('processing', 'completed', 'awaiting_documents', 'failed', name='claim_status', create_type=False), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.CheckConstraint("trigger IN ('submit','documents_added','claim_type_override','manual')", name=op.f('ck_claim_runs_trigger_valid')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_runs_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_runs')),
    sa.UniqueConstraint('claim_id', 'run_number', name='run_number')
    )
    op.create_index('claim_runs_one_active', 'claim_runs', ['claim_id'], unique=True, postgresql_where=sa.text('finished_at IS NULL'))
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_ref', sa.Text(), nullable=False),
    sa.Column('capture_stage', postgresql.ENUM('scene', 'zone', 'item', name='capture_stage', create_type=False), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('geotag_lat', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('geotag_lon', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('gyroscope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_attestation_ok', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_reasons', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('vision_processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(geotag_lat IS NULL) = (geotag_lon IS NULL)', name=op.f('ck_evidence_geotag_paired')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('claim_id', 'evidence_ref', name='evidence_ref')
    )
    op.create_index('evidence_claim', 'evidence', ['claim_id'], unique=False)
    op.create_index('evidence_sha256', 'evidence', ['sha256'], unique=False)
    op.create_table('line_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('item_ref', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('category', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), server_default=sa.text('1'), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=True),
    sa.Column('vision_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'vision'"), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('depreciation_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('net_loss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('value_source', postgresql.ENUM('invoice_matched', 'catalog_estimate', 'unvalued', name='value_source', create_type=False), server_default=sa.text("'unvalued'"), nullable=False),
    sa.Column('original_quantity_claimed', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('quantity_capped', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('plausibility_notes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('policy_status', postgresql.ENUM('covered', 'excluded', 'review', name='policy_status', create_type=False), nullable=True),
    sa.Column('policy_clause', sa.Text(), nullable=True),
    sa.Column('policy_reasoning', sa.Text(), nullable=True),
    sa.Column('clause_grounded', sa.Boolean(), nullable=True),
    sa.CheckConstraint("source IN ('vision','user_confirmed')", name=op.f('ck_line_items_source_valid')),
    sa.CheckConstraint("value_source <> 'invoice_matched' OR unit_value IS NOT NULL", name=op.f('ck_line_items_valued_needs_price')),
    sa.CheckConstraint('NOT quantity_capped OR original_quantity_claimed IS NOT NULL', name=op.f('ck_line_items_capped_records_original')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_line_items_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_items')),
    sa.UniqueConstraint('claim_id', 'item_ref', name='item_ref')
    )
    op.create_index('line_items_serial', 'line_items', ['serial_number'], unique=False, postgresql_where=sa.text('serial_number IS NOT NULL'))
    op.create_table('claim_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('kind', postgresql.ENUM('warning', 'anomaly', 'intake_reason', 'doc_gate_reason', 'gateway_blocking_reason', name='note_kind', create_type=False), nullable=False),
    sa.Column('node_name', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_notes_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['claim_runs.id'], name=op.f('fk_claim_notes_run_id_claim_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_notes'))
    )
    op.create_index('claim_notes_lookup', 'claim_notes', ['claim_id', 'kind', 'ordinal'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('document_ref', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('requirement_id', sa.Text(), nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('invoice_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('added_in_run', sa.UUID(), nullable=True),
    sa.Column('extracted_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('extracted_unit_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extracted_description', sa.Text(), nullable=True),
    sa.Column('extraction_done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('classification_kind', postgresql.ENUM('policy_schedule', 'premium_receipt', 'govt_id', 'tax_invoice', 'stock_register', 'menu_or_price_list', 'marketing_or_other_commercial', 'damage_photograph', 'fir_report', 'fire_brigade_report', 'repair_estimate', 'repair_bill', 'bank_proof', 'medical_certificate', 'driving_licence', 'vehicle_rc', 'unreadable', 'unknown', name='document_kind', create_type=False), nullable=True),
    sa.Column('classification_verdict', postgresql.ENUM('match', 'unverified', 'mismatch', name='triage_verdict', create_type=False), nullable=True),
    sa.Column('classification_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('classification_legible', sa.Boolean(), nullable=True),
    sa.Column('classification_markers', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('classification_done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['added_in_run'], ['claim_runs.id'], name=op.f('fk_documents_added_in_run_claim_runs')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_documents_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('claim_id', 'document_ref', name='document_ref')
    )
    op.create_index('documents_claim_type', 'documents', ['claim_id', 'document_type'], unique=False)
    op.create_index('documents_sha256', 'documents', ['sha256'], unique=False)
    op.create_index('documents_untriaged', 'documents', ['claim_id'], unique=False, postgresql_where=sa.text('NOT classification_done'))
    op.create_table('line_item_evidence',
    sa.Column('line_item_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_line_item_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], name=op.f('fk_line_item_evidence_line_item_id_line_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_item_id', 'evidence_id', name=op.f('pk_line_item_evidence'))
    )
    op.create_table('line_item_documents',
    sa.Column('line_item_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_line_item_documents_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], name=op.f('fk_line_item_documents_line_item_id_line_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_item_id', 'document_id', name=op.f('pk_line_item_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_item_documents')
    op.drop_table('line_item_evidence')
    op.drop_index('documents_untriaged', table_name='documents', postgresql_where=sa.text('NOT classification_done'))
    op.drop_index('documents_sha256', table_name='documents')
    op.drop_index('documents_claim_type', table_name='documents')
    op.drop_table('documents')
    op.drop_index('claim_notes_lookup', table_name='claim_notes')
    op.drop_table('claim_notes')
    op.drop_index('line_items_serial', table_name='line_items', postgresql_where=sa.text('serial_number IS NOT NULL'))
    op.drop_table('line_items')
    op.drop_index('evidence_sha256', table_name='evidence')
    op.drop_index('evidence_claim', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('claim_runs_one_active', table_name='claim_runs', postgresql_where=sa.text('finished_at IS NULL'))
    op.drop_table('claim_runs')
    op.drop_index('claims_user_recent', table_name='claims')
    op.drop_index('claims_open', table_name='claims', postgresql_where=sa.text("status IN ('processing','awaiting_documents')"))
    op.drop_table('claims')
    # ### end Alembic commands ###
