"""outputs and lor

Revision ID: 0006_outputs
Revises: 0005_claims
Create Date: 2026-08-09 16:36:39.274052+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006_outputs'
down_revision: Union[str, None] = '0005_claims'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_packs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('main_schedule', sa.Text(), nullable=False),
    sa.Column('rejected_items_annexure', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('pending_verification_annexure', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('excluded_items_annexure', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_draft_packs_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['claim_runs.id'], name=op.f('fk_draft_packs_run_id_claim_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_packs')),
    sa.UniqueConstraint('run_id', 'attempt', name='run_attempt')
    )
    op.create_index('draft_packs_one_final', 'draft_packs', ['run_id'], unique=True, postgresql_where=sa.text('is_final'))
    op.create_table('lor_packs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('claim_type_key', sa.Text(), nullable=True),
    sa.Column('claim_type_label', sa.Text(), nullable=True),
    sa.Column('claim_type_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('claim_type_ambiguous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ruleset_slug', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('blocking_missing', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('notes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("basis IN ('universal_only','claim_type_narrowed')", name=op.f('ck_lor_packs_basis_valid')),
    sa.CheckConstraint("revision > 1 OR basis = 'universal_only'", name=op.f('ck_lor_packs_rev1_is_universal')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_lor_packs_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['claim_runs.id'], name=op.f('fk_lor_packs_run_id_claim_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lor_packs')),
    sa.UniqueConstraint('claim_id', 'revision', name='revision')
    )
    op.create_table('reserve_estimates',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('confirmed', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('conditional', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('excluded', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('unclassified', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('pending', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('screened_out', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_reserve_estimates_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['claim_runs.id'], name=op.f('fk_reserve_estimates_run_id_claim_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_reserve_estimates'))
    )
    op.create_table('lor_requirement_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lor_pack_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', postgresql.ENUM('satisfied', 'unverified', 'missing', name='req_status', create_type=False), nullable=False),
    sa.Column('severity', postgresql.ENUM('blocking', 'advisory', name='req_severity', create_type=False), nullable=False),
    sa.Column('verification', postgresql.ENUM('classified', 'attested', name='req_verification', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lor_pack_id'], ['lor_packs.id'], name=op.f('fk_lor_requirement_results_lor_pack_id_lor_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lor_requirement_results')),
    sa.UniqueConstraint('lor_pack_id', 'requirement_id', name='lor_pack_requirement')
    )
    op.create_table('proof_receipts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('draft_pack_id', sa.UUID(), nullable=True),
    sa.Column('receipt_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_proof_receipts_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_pack_id'], ['draft_packs.id'], name=op.f('fk_proof_receipts_draft_pack_id_draft_packs')),
    sa.ForeignKeyConstraint(['run_id'], ['claim_runs.id'], name=op.f('fk_proof_receipts_run_id_claim_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_receipts')),
    sa.UniqueConstraint('run_id', 'receipt_hash', name='receipt_hash')
    )
    op.create_table('qc_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('draft_pack_id', sa.UUID(), nullable=False),
    sa.Column('pass_qc', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('check_source', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_source IN ('deterministic','llm')", name=op.f('ck_qc_results_check_source_valid')),
    sa.ForeignKeyConstraint(['draft_pack_id'], ['draft_packs.id'], name=op.f('fk_qc_results_draft_pack_id_draft_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_results'))
    )
    op.create_table('lor_result_documents',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('document_ref', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['lor_requirement_results.id'], name=op.f('fk_lor_result_documents_result_id_lor_requirement_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', 'document_ref', name=op.f('pk_lor_result_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lor_result_documents')
    op.drop_table('qc_results')
    op.drop_table('proof_receipts')
    op.drop_table('lor_requirement_results')
    op.drop_table('reserve_estimates')
    op.drop_table('lor_packs')
    op.drop_index('draft_packs_one_final', table_name='draft_packs', postgresql_where=sa.text('is_final'))
    op.drop_table('draft_packs')
    # ### end Alembic commands ###
