"""policies

Revision ID: 0007_policies
Revises: 0006_outputs
Create Date: 2026-08-09 17:02:10.971574+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007_policies'
down_revision: Union[str, None] = '0006_outputs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('insurer_id', sa.UUID(), nullable=True),
    sa.Column('policy_number', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('excess', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('asset_categories', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('clauses_text', sa.Text(), nullable=True),
    sa.Column('clauses_assumed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('terms_source', sa.Text(), nullable=True),
    sa.Column('assumed_fields', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('premises_lat', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('premises_lon', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(premises_lat IS NULL) = (premises_lon IS NULL)', name=op.f('ck_policies_premises_geo_paired')),
    sa.CheckConstraint('excess IS NULL OR excess >= 0', name=op.f('ck_policies_excess_non_negative')),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date < end_date', name=op.f('ck_policies_policy_period_ordered')),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], name=op.f('fk_policies_insurer_id_insurers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index('policies_number_uq', 'policies', ['insurer_id', 'policy_number'], unique=True, postgresql_where=sa.text('policy_number IS NOT NULL'))
    op.create_table('policy_clauses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_clauses_policy_id_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_clauses')),
    sa.UniqueConstraint('policy_id', 'ordinal', name='clause_ordinal')
    )
    op.create_table('policy_sums_insured',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('category_label', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_policy_sums_insured_amount_non_negative')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_sums_insured_policy_id_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id', 'category_key', name=op.f('pk_policy_sums_insured'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_sums_insured')
    op.drop_table('policy_clauses')
    op.drop_index('policies_number_uq', table_name='policies', postgresql_where=sa.text('policy_number IS NOT NULL'))
    op.drop_table('policies')
    # ### end Alembic commands ###
